# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityenergygroup',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityenergygroup',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
