# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEnergyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name the gorup uses to describe itself. Be careful to get this right as the URL will be automatically generated from this value and it's best if URLs don't change.", max_length=500)),
                ('slug', models.SlugField(help_text='This will form the URL for this group. Try not to change this as it will break the URL.')),
                ('legal_name', models.CharField(blank=True, help_text='The legal name as registered with companies house or other registrar, e.g. Liverpool Community Renewables Limited', max_length=500, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Use country code, e.g. +44151002233', max_length=128, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postcode_source_url', models.URLField(blank=True, help_text='The source URL where the postcode information came from.', null=True)),
                ('group_source_url', models.URLField(blank=True, help_text='The source URL where the existence of this community energy group was found.', null=True)),
            ],
        ),
    ]
