# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_add_help_text_to_sender_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='private_story',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sender',
            name='profile_story',
            field=models.TextField(help_text='A short summary will help people who need support find a letter writer they can relate to.'),
        ),
    ]
