# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0003_add_private_story_field_to_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='private_story',
            field=models.TextField(blank=True),
        ),
    ]
