# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0004_make_private_story_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='age',
            field=models.IntegerField(blank=True, help_text='This will help people who want to receive a letter make a decision about who writes to them.', null=True),
        ),
    ]
