# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0005_make_age_optional_in_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='profile_story',
            field=models.TextField(blank=True, help_text='A short summary will help people who need support find a letter writer they can relate to.'),
        ),
    ]
