# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0006_make_profile_story_optional_in_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='private_story',
            field=models.TextField(blank=True, help_text="This is what you told us about your debt situation - we're showing it to you here to help you write a couple of sentences about how you got into debt."),
        ),
    ]
