# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0007_add_help_text_for_private_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
