# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0008_add_receiver_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderReceiverPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaker.Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaker.Sender')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='senderreceiverpairing',
            unique_together=set([('sender', 'receiver')]),
        ),
    ]
