# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0009_add_sender_receiver_pairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='training_complete',
            field=models.BooleanField(default=False),
        ),
    ]
