# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0010_add_training_complete_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receiver',
            new_name='Reader',
        ),
        migrations.RenameModel(
            old_name='Sender',
            new_name='Writer',
        ),
        migrations.RenameModel(
            old_name='SenderReceiverPairing',
            new_name='WriterReaderPairing',
        ),
        migrations.RenameField(
            model_name='writerreaderpairing',
            old_name='receiver',
            new_name='reader',
        ),
        migrations.RenameField(
            model_name='writerreaderpairing',
            old_name='sender',
            new_name='writer',
        ),
        migrations.AlterUniqueTogether(
            name='writerreaderpairing',
            unique_together=set([('writer', 'reader')]),
        ),
    ]
