# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0011_rename_sender_and_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='available_to_pick',
            field=models.BooleanField(default=False, help_text='This controls whether this writer will be visible for readers to to pick.'),
        ),
    ]
