# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0012_add_available_to_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='get_started_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
