# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0013_make_get_started_emails_sent_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='first_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
