# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0016_reader_postal_address_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='baseline_wellbeing_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
