# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0018_add_updated_at_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
