# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0019_make_created_at_and_updated_at_automatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='postal_address_email_sent',
        ),
    ]
