# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0020_remove_reader_postal_address_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='chase_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='follow_up_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='got_postal_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reader',
            name='invite_to_pick_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='prefer_forward_via_co_op',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='reader',
            name='priming_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='chase_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='final_chase_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='follow_up_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='priming_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='profile_reminder_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
