# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0023_sort_reader_writer_by_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='baseline_survey_complete',
            field=models.BooleanField(default=False),
        ),
    ]
