# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0024_reader_baseline_survey_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WriterReaderPairing',
            new_name='WriterReaderSelection',
        ),
    ]
