# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import letters.apps.matchmaker.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchmaker', '0026_add_created_at_to_writer_reader_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterReaderAllocation',
            fields=[
                ('reference', models.CharField(default=letters.apps.matchmaker.utils.generate_reference, editable=False, max_length=7, primary_key=True, serialize=False)),
                ('allocated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('letter_sent', models.NullBooleanField(default=None)),
                ('letter_received', models.NullBooleanField(default=None)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaker.Reader')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaker.Writer')),
            ],
            options={
                'ordering': ('-allocated_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='writerreaderallocation',
            unique_together=set([('writer', 'reader')]),
        ),
    ]
