# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0027_add_writer_reader_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerreaderselection',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='matchmaker.Reader'),
        ),
    ]
