# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0028_change_related_name_of_selections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='follow_up_email_sent',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='priming_email_sent',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='follow_up_email_sent',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='priming_email_sent',
        ),
        migrations.AddField(
            model_name='writerreaderallocation',
            name='reader_follow_up_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writerreaderallocation',
            name='reader_priming_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writerreaderallocation',
            name='writer_follow_up_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writerreaderallocation',
            name='writer_priming_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
