# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0029_move_priming_and_follow_up_fields_to_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerreaderallocation',
            name='reader_got_letter_closure_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writerreaderallocation',
            name='reader_no_letter_closure_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writerreaderallocation',
            name='writer_midway_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writerreaderallocation',
            name='writer_no_sent_letter_closure_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='writerreaderallocation',
            name='writer_sent_letter_closure_email_sent',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
