# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0030_add_extra_email_sent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerreaderallocation',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='matchmaker.Reader'),
        ),
        migrations.AlterField(
            model_name='writerreaderallocation',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='matchmaker.Writer'),
        ),
    ]
