# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0032_add_profile_approved_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='profile_reminder_email_sent',
        ),
    ]
